# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: nklmilojevic.sofka
PackageVersion: 0.29.3
PackageLocale: en-US
Publisher: nklmilojevic
PublisherUrl: https://github.com/nklmilojevic
PublisherSupportUrl: https://github.com/nklmilojevic/sofka/issues
PackageName: sofka
PackageUrl: https://github.com/nklmilojevic/sofka
License: MIT OR Apache-2.0
ShortDescription: Kubernetes terminal interface
Moniker: sofka
Tags:
  - kubernetes
  - terminal
  - tui
ReleaseNotesUrl: https://github.com/nklmilojevic/sofka/releases/tag/v0.29.3
ManifestType: defaultLocale
ManifestVersion: 1.12.0
