//! `sofka import k9s`: carry a k9s setup over to sofka.
//!
//! The importer reads k9s's own files (`config.yaml`, `aliases.yaml`,
//! `plugins.yaml` and the `plugins/` directory, `hotkeys.yaml`, `views.yaml`,
//! and the per-context `clusters/<cluster>/<context>/` files) and writes sofka
//! YAML next to the user's config: one drop-in, `conf.d/00-k9s.yaml`, plus one
//! override file per k9s context that carried a real setting. It never edits a
//! file it did not generate, and a setting the base sofka config already sets
//! keeps the user's value. Everything that does not translate is reported, so
//! nothing is dropped silently.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use toml::{Table, Value};

/// First line of every generated file; also how a re-import recognizes the
/// files it may replace.
pub const MARKER: &str = "# Generated by `sofka import k9s`.";

const DROPIN: &str = "conf.d/00-k9s.yaml";

#[derive(clap::Args, Debug, Clone)]
pub struct ImportArgs {
    #[command(subcommand)]
    pub source: ImportSource,
}

#[derive(clap::Subcommand, Debug, Clone)]
pub enum ImportSource {
    /// Convert k9s config, aliases, plugins, hotkeys, views, and per-context settings.
    K9s {
        /// k9s config directory. Default: $K9S_CONFIG_DIR, then the k9s XDG location.
        #[arg(long, value_name = "DIR", value_hint = clap::ValueHint::DirPath)]
        from: Option<PathBuf>,
        /// Print the files that would be written, without writing them.
        #[arg(long)]
        dry_run: bool,
        /// Replace files written by an earlier import.
        #[arg(long)]
        force: bool,
    },
}

pub fn run(args: &ImportArgs) -> Result<(), String> {
    let ImportSource::K9s {
        from,
        dry_run,
        force,
    } = &args.source;
    let sources = match from {
        Some(dir) => Sources::at(dir)?,
        None => Sources::locate()?,
    };
    let (loader, _) = crate::config::ConfigLoader::load();
    let dir = loader
        .dir()
        .ok_or("cannot determine the sofka config directory: set XDG_CONFIG_HOME or HOME")?
        .to_path_buf();
    let user = UserConfig::read(&loader);
    let plan = plan(&sources, &user);
    for line in apply(&plan, &dir, *dry_run, *force)? {
        println!("{line}");
    }
    Ok(())
}

/// Where the k9s files live: the config directory (`config.yaml`,
/// `aliases.yaml`, …) and the directories that may hold `clusters/` and
/// `plugins/`, in k9s's own lookup order.
#[derive(Debug, Clone, PartialEq)]
pub struct Sources {
    pub config: PathBuf,
    pub data: Vec<PathBuf>,
}

#[derive(Debug, Clone, Copy, PartialEq)]
enum Platform {
    Linux,
    MacOs,
    Windows,
}

const CONFIG_FILES: &[&str] = &[
    "config.yaml",
    "aliases.yaml",
    "plugins.yaml",
    "hotkeys.yaml",
    "views.yaml",
];

impl Sources {
    /// Read everything from one directory, as k9s does with `K9S_CONFIG_DIR`.
    pub fn at(dir: &Path) -> Result<Self, String> {
        if !dir.is_dir() {
            return Err(format!("{} is not a directory", dir.display()));
        }
        Ok(Self {
            config: dir.to_path_buf(),
            data: vec![dir.to_path_buf()],
        })
    }

    /// Find the k9s directories the way k9s does (adrg/xdg), so the import
    /// reads the same files k9s would.
    pub fn locate() -> Result<Self, String> {
        let platform = if cfg!(target_os = "macos") {
            Platform::MacOs
        } else if cfg!(windows) {
            Platform::Windows
        } else {
            Platform::Linux
        };
        let home = crate::config::home_dir().map(PathBuf::from);
        let (config, data) = candidates(platform, |name| std::env::var_os(name), home);
        let found = config.iter().find(|dir| holds_k9s_config(dir));
        let Some(found) = found else {
            let searched: Vec<String> = config.iter().map(|d| d.display().to_string()).collect();
            return Err(format!(
                "no k9s configuration found (searched {}); pass --from DIR",
                searched.join(", ")
            ));
        };
        let mut dirs = vec![found.clone()];
        dirs.extend(data.into_iter().filter(|d| d.is_dir() && d != found));
        Ok(Self {
            config: found.clone(),
            data: dirs,
        })
    }
}

fn holds_k9s_config(dir: &Path) -> bool {
    CONFIG_FILES.iter().any(|f| dir.join(f).is_file())
        || dir.join("clusters").is_dir()
        || dir.join("plugins").is_dir()
}

/// The user's own sofka settings around the import, as sofka merges them:
/// `before` is what the drop-in is merged over (the base config and drop-ins
/// that sort earlier), `after` the drop-ins merged after it.
#[derive(Debug, Default)]
pub struct UserConfig {
    pub before: Option<Value>,
    pub after: Vec<Value>,
}

impl UserConfig {
    fn read(loader: &crate::config::ConfigLoader) -> Self {
        let dropin = Path::new(DROPIN).file_name();
        let mut before = loader.base_value().cloned().into_iter().collect::<Vec<_>>();
        let mut after = Vec::new();
        for path in loader.dropin_paths() {
            if generated(&path) {
                continue;
            }
            let Ok(Some(layer)) = crate::config::read_layer(&path) else {
                continue;
            };
            if path.file_name() < dropin {
                before.push(layer);
            } else {
                after.push(layer);
            }
        }
        Self {
            before: (!before.is_empty()).then(|| crate::config::merge_layers(before)),
            after,
        }
    }
}

/// Candidate config and data directories, most specific first.
fn candidates(
    platform: Platform,
    var: impl Fn(&str) -> Option<std::ffi::OsString>,
    home: Option<PathBuf>,
) -> (Vec<PathBuf>, Vec<PathBuf>) {
    let var = |name: &str| var(name).filter(|v| !v.is_empty()).map(PathBuf::from);
    if let Some(dir) = var("K9S_CONFIG_DIR") {
        return (vec![dir.clone()], vec![dir]);
    }
    let mut config = Vec::new();
    let mut data = Vec::new();
    if let Some(dir) = var("XDG_CONFIG_HOME") {
        config.push(dir.join("k9s"));
    }
    if let Some(dir) = var("XDG_DATA_HOME") {
        data.push(dir.join("k9s"));
    }
    match platform {
        Platform::Windows => {
            if let Some(dir) = var("LOCALAPPDATA") {
                config.push(dir.join("k9s"));
                data.push(dir.join("k9s"));
            }
        }
        Platform::MacOs => {
            if let Some(home) = &home {
                let dir = home.join("Library").join("Application Support").join("k9s");
                config.push(dir.clone());
                data.push(dir);
            }
        }
        Platform::Linux => {}
    }
    if let Some(home) = &home {
        config.push(home.join(".config").join("k9s"));
        data.push(home.join(".local").join("share").join("k9s"));
    }
    config.dedup();
    data.dedup();
    (config, data)
}

/// One file the import produces, relative to the sofka config directory.
#[derive(Debug, Clone)]
pub struct Output {
    pub path: PathBuf,
    pub doc: Table,
    /// Where the settings came from, for the report.
    pub label: String,
}

#[derive(Debug, Default)]
pub struct Plan {
    pub source: PathBuf,
    pub outputs: Vec<Output>,
    /// k9s settings that were not imported, with the reason.
    pub skipped: Vec<String>,
    /// Imported settings dropped because the base sofka config already sets them.
    pub kept: Vec<String>,
    /// The user's settings merged with the imported global ones, as a context
    /// override file inherits them.
    pub effective: Option<Value>,
    /// k9s files that exist but could not be read. Their settings are missing
    /// from the plan, not removed, so earlier imports of them are kept.
    pub unreadable: Vec<PathBuf>,
}

// ---------------------------------------------------------------------------
// k9s file shapes. Unknown fields are ignored: the importer reads what it
// can translate and reports the settings it recognizes but cannot carry over.
// ---------------------------------------------------------------------------

#[derive(Debug, Default, Deserialize)]
#[serde(default)]
struct MainFile {
    k9s: Settings,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "camelCase")]
struct Settings {
    read_only: Option<bool>,
    default_view: Option<String>,
    port_forward_address: Option<String>,
    ui: Ui,
    logger: Logger,
    thresholds: Thresholds,
    shell_pod: Option<ShellPod>,
    image_scans: Option<ImageScans>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "camelCase")]
struct Ui {
    enable_mouse: Option<bool>,
    headless: Option<bool>,
    skin: Option<String>,
    defaults_to_full_screen: Option<bool>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "camelCase")]
struct Logger {
    tail: Option<i64>,
    buffer: Option<i64>,
    since_seconds: Option<i64>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default)]
struct Thresholds {
    cpu: Option<Band>,
    memory: Option<Band>,
}

#[derive(Debug, Default, Deserialize, PartialEq, Clone, Copy)]
#[serde(default)]
struct Band {
    critical: Option<i64>,
    warn: Option<i64>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default)]
struct ShellPod {
    image: Option<String>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default)]
struct ImageScans {
    enable: bool,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default)]
struct ContextFile {
    k9s: ContextSettings,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "camelCase")]
struct ContextSettings {
    read_only: Option<bool>,
    skin: Option<String>,
    namespace: ContextNamespace,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "camelCase")]
struct ContextNamespace {
    favorites: Vec<String>,
    lock_favorites: bool,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default)]
struct AliasFile {
    aliases: BTreeMap<String, serde_yaml::Value>,
}

impl AliasFile {
    /// The alias map. Older k9s releases wrote it nested, as
    /// `aliases: {aliases: {...}}`.
    fn entries(&self) -> BTreeMap<String, String> {
        let flat = match self.aliases.get("aliases") {
            Some(serde_yaml::Value::Mapping(inner)) => inner
                .iter()
                .filter_map(|(k, v)| Some((k.as_str()?.to_string(), v.clone())))
                .collect(),
            _ => self.aliases.clone(),
        };
        flat.into_iter()
            .filter_map(|(k, v)| Some((k, v.as_str()?.to_string())))
            .collect()
    }
}

#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "camelCase")]
struct HotkeyFile {
    hot_keys: BTreeMap<String, Hotkey>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "camelCase")]
struct Hotkey {
    short_cut: String,
    command: String,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default)]
struct ViewFile {
    views: BTreeMap<String, View>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "camelCase")]
struct View {
    sort_column: Option<String>,
    columns: Vec<String>,
}

#[derive(Debug, Default, Deserialize, Clone)]
#[serde(default, rename_all = "camelCase")]
struct K9sPlugin {
    short_cut: String,
    #[serde(rename = "override")]
    overrides: bool,
    scopes: Vec<String>,
    command: String,
    args: Vec<serde_yaml::Value>,
    background: bool,
    confirm: Option<bool>,
    dangerous: bool,
    pipes: Vec<String>,
    inputs: Vec<K9sInput>,
}

#[derive(Debug, Default, Deserialize, Clone)]
#[serde(default)]
struct K9sInput {
    name: String,
    #[serde(rename = "type")]
    kind: String,
    required: bool,
    default: Option<serde_yaml::Value>,
    options: Vec<String>,
}

/// k9s defaults, written into every `config.yaml` it creates. A value equal
/// to its k9s default is not a user choice and is not imported.
const K9S_LOG_TAIL: i64 = 100;
const K9S_LOG_BUFFER: i64 = 5000;
const K9S_LOG_SINCE: i64 = -1;
const K9S_BAND: Band = Band {
    critical: Some(90),
    warn: Some(70),
};

// ---------------------------------------------------------------------------
// Planning
// ---------------------------------------------------------------------------

/// Read the k9s files under `src` and build the sofka files to write.
/// Settings the user's sofka config already sets win.
pub fn plan(src: &Sources, user: &UserConfig) -> Plan {
    let mut plan = Plan {
        source: src.config.clone(),
        ..Plan::default()
    };
    let skipped = &mut plan.skipped;
    let mut unreadable = Vec::new();
    let mut doc = Table::new();

    let main: Option<MainFile> = read(&src.config.join("config.yaml"), skipped, &mut unreadable);
    let main = main.unwrap_or_default().k9s;
    convert_settings(&main, &mut doc, skipped);

    if let Some(file) =
        read::<AliasFile>(&src.config.join("aliases.yaml"), skipped, &mut unreadable)
    {
        convert_aliases(&file.entries(), &mut doc, skipped);
    }

    let mut plugins = read_plugins(&src.config.join("plugins.yaml"), skipped, &mut unreadable);
    let mut plugin_dirs: Vec<PathBuf> = src.data.iter().map(|d| d.join("plugins")).collect();
    plugin_dirs.insert(0, src.config.join("plugins"));
    plugin_dirs.dedup();
    for dir in plugin_dirs {
        for path in yaml_files(&dir) {
            plugins.extend(read_plugins(&path, skipped, &mut unreadable));
        }
    }
    convert_plugins(&plugins, &mut doc, skipped);

    if let Some(file) =
        read::<HotkeyFile>(&src.config.join("hotkeys.yaml"), skipped, &mut unreadable)
    {
        convert_hotkeys(&file.hot_keys, &mut doc, skipped);
    }

    if let Some(file) = read::<ViewFile>(&src.config.join("views.yaml"), skipped, &mut unreadable) {
        convert_views(&file.views, &mut doc, skipped);
    }

    if let Some(base) = user.before.as_ref().and_then(Value::as_table) {
        keep_base(&mut doc, base, &mut plan.kept, skipped);
    }
    if doc.contains_key("plugins") {
        doc.insert("plugins_merge".into(), "name".into());
    }

    let effective = crate::config::merge_layers(
        user.before
            .iter()
            .cloned()
            .chain([Value::Table(doc.clone())])
            .chain(user.after.iter().cloned()),
    );
    let global_bookmarks = effective.get("bookmarks").cloned();
    plan.effective = Some(effective);
    let global_skin = main.ui.skin.clone().filter(|s| !s.is_empty());
    if !doc.is_empty() {
        plan.outputs.push(Output {
            path: PathBuf::from(DROPIN),
            doc,
            label: "global settings".into(),
        });
    }

    let clusters = src
        .data
        .iter()
        .map(|d| d.join("clusters"))
        .find(|d| d.is_dir());
    if let Some(clusters) = clusters {
        for (cluster, context, dir) in context_dirs(&clusters) {
            let ctx = ContextInput {
                cluster: &cluster,
                context: &context,
                dir: &dir,
                read_only: main.read_only.unwrap_or(false),
                skin: global_skin.as_deref(),
                bookmarks: global_bookmarks.as_ref(),
            };
            if let Some(out) = convert_context(&ctx, skipped, &mut unreadable) {
                plan.outputs.push(out);
            }
        }
    }
    plan.unreadable = unreadable;
    plan
}

/// Read one k9s file. A file that exists but cannot be read or parsed is
/// reported and recorded in `unreadable`.
fn read<T: for<'de> Deserialize<'de>>(
    path: &Path,
    skipped: &mut Vec<String>,
    unreadable: &mut Vec<PathBuf>,
) -> Option<T> {
    let text = match std::fs::read_to_string(path) {
        Ok(text) => text,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return None,
        Err(e) => {
            skipped.push(format!("{}: {e}", path.display()));
            unreadable.push(path.to_path_buf());
            return None;
        }
    };
    if text.trim().is_empty() {
        return None;
    }
    match serde_yaml::from_str(&text) {
        Ok(value) => Some(value),
        Err(e) => {
            skipped.push(format!("{}: {e}", path.display()));
            unreadable.push(path.to_path_buf());
            None
        }
    }
}

fn yaml_files(dir: &Path) -> Vec<PathBuf> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut paths: Vec<PathBuf> = entries
        .filter_map(|e| e.ok().map(|e| e.path()))
        .flat_map(|path| {
            if path.is_dir() {
                yaml_files(&path)
            } else if matches!(
                path.extension().and_then(|s| s.to_str()),
                Some("yaml" | "yml")
            ) {
                vec![path]
            } else {
                Vec::new()
            }
        })
        .collect();
    paths.sort();
    paths
}

/// Read one k9s plugin file in any of its three shapes: a `plugins:` map, a
/// bare map of plugins, or a single plugin named after the file.
fn read_plugins(
    path: &Path,
    skipped: &mut Vec<String>,
    unreadable: &mut Vec<PathBuf>,
) -> Vec<(String, K9sPlugin)> {
    let Some(value) = read::<serde_yaml::Value>(path, skipped, unreadable) else {
        return Vec::new();
    };
    let parse = |name: &str, v: serde_yaml::Value, skipped: &mut Vec<String>| {
        match serde_yaml::from_value::<K9sPlugin>(v) {
            Ok(p) => Some((name.to_string(), p)),
            Err(e) => {
                skipped.push(format!("plugin {name:?} in {}: {e}", path.display()));
                None
            }
        }
    };
    let Some(map) = value.as_mapping() else {
        skipped.push(format!("{}: not a mapping", path.display()));
        return Vec::new();
    };
    if map.contains_key("shortCut") {
        let name = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("plugin");
        return parse(name, value.clone(), skipped).into_iter().collect();
    }
    let map = match map.get("plugins") {
        Some(serde_yaml::Value::Mapping(inner)) => inner.clone(),
        Some(_) => return Vec::new(),
        None => map.clone(),
    };
    map.into_iter()
        .filter_map(|(k, v)| parse(k.as_str()?, v, skipped))
        .collect()
}

fn subdirs(dir: &Path) -> Vec<PathBuf> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut dirs: Vec<PathBuf> = entries
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.is_dir())
        .collect();
    dirs.sort();
    dirs
}

fn context_dirs(clusters: &Path) -> Vec<(String, String, PathBuf)> {
    let name = |p: &Path| p.file_name().map(|s| s.to_string_lossy().into_owned());
    let mut found = Vec::new();
    for cluster in subdirs(clusters) {
        for context in subdirs(&cluster) {
            if let (Some(c), Some(x)) = (name(&cluster), name(&context)) {
                found.push((c, x, context));
            }
        }
    }
    found
}

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

fn convert_settings(k: &Settings, doc: &mut Table, skipped: &mut Vec<String>) {
    if k.read_only == Some(true) {
        doc.insert("readonly".into(), true.into());
    }
    if let Some(view) = k.default_view.as_deref().map(str::trim)
        && !view.is_empty()
    {
        doc.insert("default_resource".into(), alias_target(view).into());
    }
    if k.ui.enable_mouse == Some(true) {
        doc.insert("mouse".into(), true.into());
    }
    if k.ui.headless == Some(true) {
        doc.insert("hide_header".into(), true.into());
    }
    if let Some(name) = k.ui.skin.as_deref().filter(|s| !s.is_empty()) {
        match skin(name) {
            Some((sofka, exact)) => {
                if !exact {
                    skipped.push(format!(
                        "skin {name:?}: no exact sofka match, using {sofka:?}"
                    ));
                }
                table(doc, "skin").insert("name".into(), sofka.into());
            }
            None => skipped.push(format!(
                "skin {name:?}: no sofka equivalent, keeping automatic dark/light detection (`:skin` lists the built-in skins)"
            )),
        }
    }

    let mut logs = Table::new();
    if let Some(tail) = k.logger.tail.filter(|t| *t != K9S_LOG_TAIL) {
        logs.insert("tail".into(), tail.into());
    }
    if let Some(buffer) = k.logger.buffer.filter(|b| *b != K9S_LOG_BUFFER && *b > 0) {
        logs.insert("buffer".into(), buffer.into());
    }
    if let Some(since) = k
        .logger
        .since_seconds
        .filter(|s| *s != K9S_LOG_SINCE && *s > 0)
    {
        logs.insert("since".into(), format!("{since}s").into());
    }
    if k.ui.defaults_to_full_screen == Some(true) {
        logs.insert("fullscreen".into(), true.into());
    }
    if !logs.is_empty() {
        doc.insert("logs".into(), Value::Table(logs));
    }

    let cpu = k.thresholds.cpu.unwrap_or(K9S_BAND);
    let memory = k.thresholds.memory.unwrap_or(K9S_BAND);
    let chosen = if cpu != K9S_BAND { cpu } else { memory };
    if chosen != K9S_BAND {
        if cpu != memory {
            let (used, other) = if cpu != K9S_BAND {
                ("CPU", "memory")
            } else {
                ("memory", "CPU")
            };
            skipped.push(format!(
                "thresholds: sofka has one utilization band for CPU and memory; used the {used} values, not the {other} values"
            ));
        }
        let mut band = Table::new();
        if let Some(warn) = chosen.warn {
            band.insert("warn".into(), warn.into());
        }
        if let Some(critical) = chosen.critical {
            band.insert("critical".into(), critical.into());
        }
        table(doc, "thresholds").insert("utilization".into(), Value::Table(band));
    }

    if let Some(image) = k.shell_pod.as_ref().and_then(|s| s.image.as_deref())
        && !image.is_empty()
        && !image.starts_with("busybox")
    {
        skipped.push(format!(
            "shellPod image {image:?}: set it as the node debug image under [debug] by hand"
        ));
    }
    if k.image_scans.as_ref().is_some_and(|s| s.enable) {
        skipped.push("imageScans: sofka has no image vulnerability scanning".into());
    }
    if let Some(addr) = k.port_forward_address.as_deref()
        && !matches!(addr, "" | "localhost" | "127.0.0.1")
    {
        skipped.push(format!(
            "portForwardAddress {addr:?}: sofka port-forwards bind to localhost"
        ));
    }
}

/// Map a k9s skin name onto a sofka built-in skin. The flag is false when the
/// match is a close relative rather than the same palette.
fn skin(name: &str) -> Option<(String, bool)> {
    let name = name.trim().to_ascii_lowercase();
    let name = name.strip_suffix(".yaml").unwrap_or(&name);
    let base = name.strip_suffix("-transparent").unwrap_or(name);
    if crate::theme::builtin(base).is_some() {
        return Some((base.to_string(), true));
    }
    let close = match base {
        "gruvbox-dark-hard"
        | "gruvbox-material-dark-hard"
        | "gruvbox-material-dark-medium"
        | "gruvbox-material-dark-soft" => "gruvbox-dark",
        "gruvbox-light-hard"
        | "gruvbox-material-light-hard"
        | "gruvbox-material-light-medium"
        | "gruvbox-material-light-soft" => "gruvbox-light",
        "rose-pine-moon" => "rose-pine",
        "tokyonight" | "tokyonight-night" | "tokyonight-storm" | "tokyo-night-storm" => {
            "tokyo-night"
        }
        "solarized-16" => "solarized-dark",
        _ => return None,
    };
    Some((close.to_string(), false))
}

fn table<'a>(doc: &'a mut Table, key: &str) -> &'a mut Table {
    doc.entry(key)
        .or_insert_with(|| Value::Table(Table::new()))
        .as_table_mut()
        .expect("importer tables are only created here")
}

// ---------------------------------------------------------------------------
// Aliases and hotkeys
// ---------------------------------------------------------------------------

/// k9s names resources as `group/version/plural`, `version/plural`, or a bare
/// name; sofka resolves `plural.group` or a bare name.
fn alias_target(target: &str) -> String {
    let target = target.trim().trim_start_matches(':').to_ascii_lowercase();
    let parts: Vec<&str> = target.split('/').collect();
    match parts.as_slice() {
        [group, _version, plural] if !group.is_empty() => format!("{plural}.{group}"),
        [_version, plural] => (*plural).to_string(),
        _ => target,
    }
}

fn convert_aliases(aliases: &BTreeMap<String, String>, doc: &mut Table, skipped: &mut Vec<String>) {
    for (alias, target) in aliases {
        let alias = alias.trim().to_ascii_lowercase();
        if alias.is_empty() {
            continue;
        }
        if target.split_whitespace().count() > 1 {
            // `pp: pods kube-system app=web` carries a destination, which is
            // what a sofka bookmark is.
            match navigation(target) {
                Ok(nav) => push_bookmark(doc, nav.bookmark(&alias, None)),
                Err(e) => skipped.push(format!("alias {alias:?}: {e}")),
            }
            continue;
        }
        let target = alias_target(target);
        if crate::k8s::ALIASES
            .iter()
            .any(|(a, t)| *a == alias && *t == target)
            || alias == target
        {
            continue;
        }
        table(doc, "aliases").insert(alias, target.into());
    }
}

fn convert_hotkeys(hotkeys: &BTreeMap<String, Hotkey>, doc: &mut Table, skipped: &mut Vec<String>) {
    for (name, hk) in hotkeys {
        let Some(key) = chord(&hk.short_cut) else {
            skipped.push(format!(
                "hotkey {name:?}: key {:?} has no sofka equivalent",
                hk.short_cut
            ));
            continue;
        };
        match navigation(&hk.command) {
            Ok(nav) => push_bookmark(doc, nav.bookmark(name, Some(key))),
            Err(e) => skipped.push(format!("hotkey {name:?}: {e}")),
        }
    }
}

fn push_bookmark(doc: &mut Table, bookmark: Table) {
    doc.entry("bookmarks")
        .or_insert_with(|| Value::Array(Vec::new()))
        .as_array_mut()
        .expect("importer arrays are only created here")
        .push(Value::Table(bookmark));
}

#[derive(Debug, Default, PartialEq)]
struct Navigation {
    resource: String,
    namespace: Option<String>,
    context: Option<String>,
    filter: Option<String>,
    view: Option<&'static str>,
}

impl Navigation {
    fn bookmark(&self, name: &str, key: Option<String>) -> Table {
        let mut b = Table::new();
        if let Some(key) = key {
            b.insert("key".into(), key.into());
        }
        b.insert("name".into(), name.into());
        b.insert("resource".into(), self.resource.clone().into());
        for (field, value) in [
            ("namespace", &self.namespace),
            ("context", &self.context),
            ("filter", &self.filter),
        ] {
            if let Some(v) = value {
                b.insert(field.into(), v.clone().into());
            }
        }
        if let Some(view) = self.view {
            b.insert("view".into(), view.into());
        }
        b
    }
}

/// Parse a k9s command line (`dp`, `pods kube-system`, `po app=web @prod`,
/// `xray deploy`) into a bookmark destination.
fn navigation(command: &str) -> Result<Navigation, String> {
    let mut words = command
        .trim()
        .trim_start_matches(':')
        .split_whitespace()
        .peekable();
    let first = words.next().ok_or("empty command")?.to_ascii_lowercase();
    let mut nav = Navigation::default();
    match first.as_str() {
        "x" | "xray" => {
            nav.view = Some("xray");
            nav.resource = alias_target(words.next().ok_or("xray needs a resource")?);
        }
        "pu" | "pulse" | "pulses" => {
            nav.view = Some("pulse");
            nav.resource = "pods".into();
        }
        "ctx" | "context" | "contexts" | "q" | "q!" | "quit" | "help" | "?" | "sd"
        | "screendump" | "be" | "benchmark" | "benchmarks" | "pop" | "popeye" | "dir" => {
            return Err(format!("k9s command {first:?} has no bookmark equivalent"));
        }
        _ => nav.resource = alias_target(&first),
    }
    for word in words {
        if let Some(ctx) = word.strip_prefix('@') {
            nav.context = Some(ctx.to_string());
        } else if word.contains('=') {
            nav.filter = Some(format!("-l {word}"));
        } else if nav.namespace.is_none() && !word.starts_with(['-', '/']) {
            nav.namespace = Some(word.to_string());
        } else {
            return Err(format!("cannot translate {word:?} in {command:?}"));
        }
    }
    Ok(nav)
}

/// Translate a k9s key name (tcell's `KeyNames` plus k9s's own) into a sofka
/// chord. k9s `Shift-1` is the `!` key on a US layout, and so on.
fn chord(k9s: &str) -> Option<String> {
    let k9s = k9s.trim();
    let out = if let Some(rest) = k9s.strip_prefix("Shift-") {
        let mut chars = rest.chars();
        let (c, None) = (chars.next()?, chars.next()) else {
            return None;
        };
        if c.is_ascii_alphabetic() {
            c.to_ascii_uppercase().to_string()
        } else {
            let digit = c.to_digit(10)? as usize;
            ")!@#$%^&*(".chars().nth(digit)?.to_string()
        }
    } else if let Some(rest) = k9s.strip_prefix("Ctrl-") {
        format!("ctrl-{}", rest.to_ascii_lowercase())
    } else if k9s.chars().count() == 1 {
        k9s.to_string()
    } else {
        match k9s.to_ascii_lowercase().as_str() {
            "backspace2" => "backspace".into(),
            other => other.to_string(),
        }
    };
    crate::keys::KeyChord::parse(&out).ok().map(|_| out)
}

// ---------------------------------------------------------------------------
// Plugins
// ---------------------------------------------------------------------------

const SHELLS: &[&str] = &["sh", "bash", "zsh", "dash", "ksh", "fish"];

fn convert_plugins(plugins: &[(String, K9sPlugin)], doc: &mut Table, skipped: &mut Vec<String>) {
    for (name, plugin) in plugins {
        match convert_plugin(name, plugin) {
            Ok((p, notes)) => {
                skipped.extend(notes.into_iter().map(|n| format!("plugin {name:?}: {n}")));
                doc.entry("plugins")
                    .or_insert_with(|| Value::Array(Vec::new()))
                    .as_array_mut()
                    .expect("importer arrays are only created here")
                    .retain(|v| v.get("name").and_then(Value::as_str) != Some(name));
                if let Some(Value::Array(list)) = doc.get_mut("plugins") {
                    list.push(Value::Table(p));
                }
            }
            Err(e) => skipped.push(format!("plugin {name:?}: {e}")),
        }
    }
}

/// Convert one plugin, or explain why it cannot work in sofka. The notes are
/// imported-but-different behaviours worth a line in the report.
fn convert_plugin(name: &str, p: &K9sPlugin) -> Result<(Table, Vec<String>), String> {
    let mut notes = Vec::new();
    if !p.pipes.is_empty() {
        return Err("`pipes` has no sofka equivalent; chain the commands in a shell script".into());
    }
    let key = chord(&p.short_cut)
        .ok_or_else(|| format!("key {:?} has no sofka equivalent", p.short_cut))?;
    if p.command.trim().is_empty() {
        return Err("no command".into());
    }

    let mut scopes = Vec::new();
    let mut all = p.scopes.is_empty();
    let mut containers = false;
    for scope in &p.scopes {
        let s = scope.trim().to_ascii_lowercase();
        if s == "all" {
            all = true;
        } else if s == "containers" || s == "co" {
            containers = true;
        } else {
            // sofka matches scopes against the bare plural, whatever the group.
            let plural = s.rsplit('/').next().unwrap_or(&s).to_string();
            let plural = crate::k8s::ALIASES
                .iter()
                .find(|(a, _)| *a == plural)
                .map(|(_, t)| (*t).to_string())
                .unwrap_or(plural);
            if !scopes.contains(&plural) {
                scopes.push(plural);
            }
        }
    }
    if containers {
        if !all && scopes.is_empty() {
            return Err("sofka plugins cannot target the k9s containers view".into());
        }
        notes.push("the containers scope does not exist in sofka; dropped".into());
    }

    let input_names: Vec<String> = p.inputs.iter().map(|i| i.name.clone()).collect();
    let mut args = Vec::new();
    let mut leftover = Vec::new();
    for arg in &p.args {
        let arg = yaml_string(arg);
        args.push(rewrite_arg(&arg, &input_names, &mut leftover)?);
    }
    leftover.sort();
    leftover.dedup();
    if !leftover.is_empty() {
        let shell = Path::new(p.command.trim())
            .file_name()
            .and_then(|s| s.to_str())
            .is_some_and(|c| SHELLS.contains(&c));
        let source = if shell {
            "left to the shell environment"
        } else {
            "passed through unexpanded"
        };
        notes.push(format!(
            "{} {source}; sofka has no such placeholder",
            leftover.join(", ")
        ));
    }

    let mut out = Table::new();
    out.insert("name".into(), name.into());
    out.insert("key".into(), key.into());
    out.insert("command".into(), p.command.trim().into());
    out.insert(
        "args".into(),
        Value::Array(args.into_iter().map(Value::from).collect()),
    );
    if !all {
        out.insert(
            "scopes".into(),
            Value::Array(scopes.into_iter().map(Value::from).collect()),
        );
    }
    // k9s hides a `dangerous` plugin in read-only mode and runs every other
    // one; sofka's `mutating` flag is that same switch.
    out.insert("mutating".into(), p.dangerous.into());
    if p.confirm.unwrap_or(!p.inputs.is_empty()) {
        out.insert("confirm".into(), true.into());
    }
    if p.background {
        out.insert("output".into(), "background".into());
    }
    if !p.inputs.is_empty() {
        let mut inputs = Table::new();
        for input in &p.inputs {
            let mut spec = Table::new();
            let kind = match input.kind.as_str() {
                "bool" => "boolean",
                _ => "string",
            };
            spec.insert("type".into(), kind.into());
            let default = input.default.as_ref().map(yaml_string);
            match default {
                Some(d) => {
                    spec.insert("default".into(), d.into());
                }
                None if !input.required => {
                    // An optional input still needs a value sofka accepts:
                    // a dropdown's first option, or an empty string.
                    let default = match (kind, input.options.first()) {
                        ("boolean", _) => "false".to_string(),
                        _ if input.kind == "dropdown" => {
                            input.options.first().cloned().unwrap_or_default()
                        }
                        _ => String::new(),
                    };
                    spec.insert("default".into(), default.into());
                }
                None => {}
            }
            if input.kind == "dropdown" && !input.options.is_empty() {
                spec.insert(
                    "choices".into(),
                    Value::Array(input.options.iter().cloned().map(Value::from).collect()),
                );
            }
            inputs.insert(input.name.clone(), Value::Table(spec));
        }
        out.insert("inputs".into(), Value::Table(inputs));
        out.insert("prompt".into(), "always".into());
    }
    if p.overrides {
        notes.push(format!(
            "k9s let it override a built-in key; in sofka a built-in key on {:?} wins until you rebind it under [keys]",
            p.short_cut
        ));
    }
    Ok((out, notes))
}

fn yaml_string(v: &serde_yaml::Value) -> String {
    match v {
        serde_yaml::Value::String(s) => s.clone(),
        serde_yaml::Value::Number(n) => n.to_string(),
        serde_yaml::Value::Bool(b) => b.to_string(),
        other => serde_yaml::to_string(other)
            .unwrap_or_default()
            .trim()
            .to_string(),
    }
}

/// Rewrite k9s's `$VAR` / `${VAR}` placeholders (case-insensitive in k9s) to
/// sofka's spelling. Fails for a placeholder a plugin cannot run without;
/// records the rest, which k9s would also leave alone or fill from the
/// kubeconfig, in `leftover`.
fn rewrite_arg(arg: &str, inputs: &[String], leftover: &mut Vec<String>) -> Result<String, String> {
    use std::sync::LazyLock;
    static RX: LazyLock<regex::Regex> = LazyLock::new(|| {
        regex::Regex::new(r"\$(!?)([\w\-]+)|\$\{(!?)([\w\-%/: ]+)\}").expect("valid regex")
    });

    let mut err = None;
    let whole = RX.find(arg).is_some_and(|m| m.as_str() == arg);
    let out = RX.replace_all(arg, |caps: &regex::Captures| {
        let raw = &caps[0];
        let inverse = caps.get(1).or(caps.get(3)).is_some_and(|m| !m.is_empty());
        let key = caps.get(2).or(caps.get(4)).map_or("", |m| m.as_str());
        let upper = key.to_ascii_uppercase();
        if inverse {
            err = Some(format!(
                "{raw}: inverted placeholders have no sofka equivalent"
            ));
            return raw.to_string();
        }
        match upper.as_str() {
            "NAMESPACE" | "NAME" | "CONTEXT" | "CLUSTER" | "FILTER" => format!("${upper}"),
            "RESOURCE_NAME" => "$RESOURCE".into(),
            "RESOURCE_GROUP" => "$GROUP".into(),
            "RESOURCE_VERSION" => "$VERSION".into(),
            "POD" => {
                err = Some(
                    "$POD comes from the k9s containers view, which sofka plugins cannot target"
                        .into(),
                );
                raw.to_string()
            }
            u if u.starts_with("COL-") => {
                err = Some(format!("{raw}: sofka plugins cannot read table cells"));
                raw.to_string()
            }
            u if u.starts_with("INPUT_") => {
                let name = &key["INPUT_".len()..];
                match inputs.iter().find(|i| i.eq_ignore_ascii_case(name)) {
                    Some(input) if whole => format!("${{input.{input}}}"),
                    Some(_) => {
                        err = Some(format!(
                            "{raw}: sofka passes inputs as whole arguments, not inside a string"
                        ));
                        raw.to_string()
                    }
                    None => {
                        leftover.push(raw.to_string());
                        raw.to_string()
                    }
                }
            }
            "KUBECONFIG" | "USER" | "GROUPS" => {
                leftover.push(format!("${upper}"));
                raw.to_string()
            }
            _ => raw.to_string(),
        }
    });
    match err {
        Some(e) => Err(e),
        None => Ok(out.into_owned()),
    }
}

// ---------------------------------------------------------------------------
// Views
// ---------------------------------------------------------------------------

fn convert_views(views: &BTreeMap<String, View>, doc: &mut Table, skipped: &mut Vec<String>) {
    for (key, view) in views {
        let mut columns = Vec::new();
        for spec in &view.columns {
            match column(key, spec) {
                Ok(Some(col)) => columns.push(Value::Table(col)),
                Ok(None) => {}
                Err(e) => skipped.push(format!("view {key:?} column {spec:?}: {e}")),
            }
        }
        let mut out = Table::new();
        if let Some(sort) = view.sort_column.as_deref().filter(|s| !s.is_empty()) {
            out.insert("sort".into(), sort.into());
        }
        if !columns.is_empty() {
            out.insert("replace".into(), true.into());
            out.insert("columns".into(), Value::Array(columns));
        }
        if !out.is_empty() {
            table(doc, "views").insert(key.clone(), Value::Table(out));
        }
    }
}

/// Convert one k9s column spec, `NAME[:jsonpath][|FLAGS]`. Hidden columns
/// (`H`) are dropped, which is what hiding means in a replaced view.
fn column(view: &str, spec: &str) -> Result<Option<Table>, String> {
    use std::sync::LazyLock;
    static RX: LazyLock<regex::Regex> = LazyLock::new(|| {
        regex::Regex::new(r"^([\w\s%/-]+):?([\w\W]*?)\|?([NTWSLRH]{0,3})$").expect("valid regex")
    });
    let caps = RX.captures(spec.trim()).ok_or("not a k9s column spec")?;
    let name = caps[1].trim().to_string();
    let path = caps[2].trim();
    let flags = &caps[3];
    if flags.contains('H') {
        return Ok(None);
    }
    let mut col = Table::new();
    col.insert("name".into(), name.clone().into());
    if path.is_empty() {
        match metric(view, &name) {
            Some(m) => col.insert("metric".into(), m.into()),
            None => col.insert("builtin".into(), name.into()),
        };
    } else {
        let pointer = json_pointer(path).ok_or_else(|| {
            format!(
                "JSONPath {path:?} needs filters or wildcards, which sofka columns do not support"
            )
        })?;
        col.insert("path".into(), pointer.into());
        if flags.contains('T') {
            col.insert("type".into(), "time".into());
        } else if flags.contains('N') {
            col.insert("type".into(), "number".into());
        }
    }
    if flags.contains('W') {
        col.insert("wide".into(), true.into());
    }
    if flags.contains('R') || flags.contains('N') {
        col.insert("align".into(), "right".into());
    } else if flags.contains('L') {
        col.insert("align".into(), "left".into());
    }
    Ok(Some(col))
}

/// k9s metric column headers and the sofka metric source behind each.
fn metric(view: &str, header: &str) -> Option<&'static str> {
    let nodes = view.ends_with("nodes") || view == "no" || view == "node";
    Some(match (nodes, header) {
        (true, "%CPU") => "node-cpu-utilization",
        (true, "%MEM") => "node-memory-utilization",
        (true, "CPU/R" | "%CPU/R") => "node-cpu-request",
        (true, "MEM/R" | "%MEM/R") => "node-memory-request",
        (true, "CPU/L" | "%CPU/L") => "node-cpu-limit",
        (true, "MEM/L" | "%MEM/L") => "node-memory-limit",
        (_, "CPU") => "cpu",
        (_, "MEM") => "memory",
        (false, "CPU/R") => "cpu-request",
        (false, "MEM/R") => "memory-request",
        (false, "CPU/L") => "cpu-limit",
        (false, "MEM/L") => "memory-limit",
        (false, "%CPU/R") => "cpu-request-utilization",
        (false, "%MEM/R") => "memory-request-utilization",
        (false, "%CPU/L") => "cpu-limit-utilization",
        (false, "%MEM/L") => "memory-limit-utilization",
        _ => return None,
    })
}

/// Convert a simple JSONPath (`.spec.containers[0].image`,
/// `{.metadata.labels['app\.kubernetes\.io/name']}`) into a JSON Pointer.
/// Filters, wildcards, slices, and recursive descent have no pointer form.
fn json_pointer(path: &str) -> Option<String> {
    let s = path.trim();
    let s = s
        .strip_prefix('{')
        .and_then(|s| s.strip_suffix('}'))
        .unwrap_or(s)
        .trim();
    let s = s.strip_prefix('$').unwrap_or(s);
    let s = s.strip_prefix('.').unwrap_or(s);
    if s.is_empty() {
        return None;
    }
    let mut segments = Vec::new();
    let mut seg = String::new();
    let mut after_bracket = false;
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        match c {
            '\\' => seg.push(chars.next()?),
            '.' => {
                if seg.is_empty() {
                    if !after_bracket {
                        return None;
                    }
                } else {
                    segments.push(std::mem::take(&mut seg));
                }
                after_bracket = false;
            }
            '[' => {
                if !seg.is_empty() {
                    segments.push(std::mem::take(&mut seg));
                }
                let mut raw = String::new();
                let mut quote = None;
                loop {
                    let ch = chars.next()?;
                    match (quote, ch) {
                        (None, ']') => break,
                        (None, '\'' | '"') => quote = Some(ch),
                        (Some(q), ch) if ch == q => quote = None,
                        _ => {}
                    }
                    raw.push(ch);
                }
                let raw = raw.trim();
                let inner = if let Some(key) = raw
                    .strip_prefix('\'')
                    .and_then(|r| r.strip_suffix('\''))
                    .or_else(|| raw.strip_prefix('"').and_then(|r| r.strip_suffix('"')))
                {
                    key.replace('\\', "")
                } else if !raw.is_empty() && raw.chars().all(|c| c.is_ascii_digit()) {
                    raw.to_string()
                } else {
                    return None;
                };
                if inner.is_empty() {
                    return None;
                }
                segments.push(inner);
                after_bracket = true;
            }
            '*' | '?' | '@' | '(' | ')' | ',' | ':' | ' ' | '$' => return None,
            _ => {
                if after_bracket {
                    return None;
                }
                seg.push(c);
            }
        }
    }
    if !seg.is_empty() {
        segments.push(seg);
    }
    if segments.is_empty() {
        return None;
    }
    Some(
        segments
            .iter()
            .map(|s| format!("/{}", s.replace('~', "~0").replace('/', "~1")))
            .collect(),
    )
}

// ---------------------------------------------------------------------------
// Per-context files
// ---------------------------------------------------------------------------

struct ContextInput<'a> {
    cluster: &'a str,
    context: &'a str,
    dir: &'a Path,
    read_only: bool,
    skin: Option<&'a str>,
    bookmarks: Option<&'a Value>,
}

fn convert_context(
    ctx: &ContextInput,
    skipped: &mut Vec<String>,
    unreadable: &mut Vec<PathBuf>,
) -> Option<Output> {
    let mut doc = Table::new();
    let mut notes = Vec::new();
    if let Some(file) = read::<ContextFile>(&ctx.dir.join("config.yaml"), &mut notes, unreadable) {
        let k = file.k9s;
        if let Some(ro) = k.read_only
            && ro != ctx.read_only
        {
            doc.insert("readonly".into(), ro.into());
        }
        if let Some(name) = k
            .skin
            .as_deref()
            .filter(|s| !s.is_empty() && Some(*s) != ctx.skin)
        {
            match skin(name) {
                Some((sofka, _)) => {
                    table(&mut doc, "skin").insert("name".into(), sofka.into());
                }
                None => notes.push(format!("skin {name:?}: no sofka equivalent")),
            }
        }
        // Unless `lockFavorites` is set, k9s rewrites `favorites` with the
        // namespaces visited last: history, not a pinned list. `all` is a
        // pseudo-namespace.
        let favorites: Vec<Value> = k
            .namespace
            .favorites
            .iter()
            .filter(|_| k.namespace.lock_favorites)
            .filter(|ns| !matches!(ns.as_str(), "" | "all"))
            .map(|ns| Value::from(ns.as_str()))
            .collect();
        if !favorites.is_empty() {
            doc.insert("favorite_namespaces".into(), Value::Array(favorites));
        }
    }
    // Aliases that name a destination and hotkeys both become bookmarks.
    let mut local = Table::new();
    if let Some(file) = read::<AliasFile>(&ctx.dir.join("aliases.yaml"), &mut notes, unreadable) {
        convert_aliases(&file.entries(), &mut local, &mut notes);
    }
    if let Some(aliases) = local.remove("aliases") {
        doc.insert("aliases".into(), aliases);
    }
    let plugins = read_plugins(&ctx.dir.join("plugins.yaml"), &mut notes, unreadable);
    convert_plugins(&plugins, &mut doc, &mut notes);
    if doc.contains_key("plugins") {
        doc.insert("plugins_merge".into(), "name".into());
    }
    if let Some(file) = read::<HotkeyFile>(&ctx.dir.join("hotkeys.yaml"), &mut notes, unreadable) {
        convert_hotkeys(&file.hot_keys, &mut local, &mut notes);
    }
    if let Some(Value::Array(own)) = local.remove("bookmarks") {
        // A bookmarks list in an override replaces the inherited one; k9s
        // adds context hotkeys to the global ones, so carry both.
        let mut all = match ctx.bookmarks {
            Some(Value::Array(inherited)) => inherited.clone(),
            _ => Vec::new(),
        };
        all.extend(own);
        doc.insert("bookmarks".into(), Value::Array(all));
    }
    let label = format!("context {:?} on cluster {:?}", ctx.context, ctx.cluster);
    skipped.extend(notes.into_iter().map(|n| format!("{label}: {n}")));
    if doc.is_empty() {
        return None;
    }
    Some(Output {
        path: PathBuf::from("clusters")
            .join(crate::config::sanitize(ctx.cluster))
            .join(crate::config::sanitize(ctx.context))
            .join("config.yaml"),
        doc,
        label,
    })
}

// ---------------------------------------------------------------------------
// The user's existing sofka config wins
// ---------------------------------------------------------------------------

/// Drop imported settings the base sofka config already sets: the drop-in is
/// merged over the base, so leaving them in would override the user's own
/// choice. Plugins merge by name; bookmarks, a list a drop-in would replace,
/// are carried over from the base so both survive.
fn keep_base(doc: &mut Table, base: &Table, kept: &mut Vec<String>, skipped: &mut Vec<String>) {
    let names = |v: Option<&Value>, field: &str| -> Vec<String> {
        v.and_then(Value::as_array)
            .map(|a| {
                a.iter()
                    .filter_map(|p| p.get(field).and_then(Value::as_str).map(String::from))
                    .collect()
            })
            .unwrap_or_default()
    };
    if let Some(Value::Array(list)) = doc.get_mut("plugins") {
        let base_names = names(base.get("plugins"), "name");
        list.retain(|p| {
            let name = p.get("name").and_then(Value::as_str).unwrap_or_default();
            let clash = base_names.iter().any(|n| n == name);
            if clash {
                kept.push(format!("plugin {name:?}"));
            }
            !clash
        });
        if list.is_empty() {
            doc.remove("plugins");
        }
    }
    if let (Some(Value::Array(own)), Some(Value::Array(theirs))) =
        (doc.get("bookmarks"), base.get("bookmarks"))
    {
        let base_names = names(base.get("bookmarks"), "name");
        let base_keys = names(base.get("bookmarks"), "key");
        let mut merged = theirs.clone();
        for b in own {
            let name = b.get("name").and_then(Value::as_str).unwrap_or_default();
            let key = b.get("key").and_then(Value::as_str);
            if base_names.iter().any(|n| n == name)
                || key.is_some_and(|k| base_keys.iter().any(|b| b == k))
            {
                skipped.push(format!(
                    "hotkey {name:?}: your sofka config has a bookmark with that name or key"
                ));
            } else {
                merged.push(b.clone());
            }
        }
        doc.insert("bookmarks".into(), Value::Array(merged));
    }
    let mut base = base.clone();
    for key in ["plugins", "bookmarks", "plugins_merge", "plugins_remove"] {
        base.remove(key);
    }
    keep_tables(doc, &base, "", kept);
}

fn keep_tables(doc: &mut Table, base: &Table, path: &str, kept: &mut Vec<String>) {
    let keys: Vec<String> = doc.keys().cloned().collect();
    for key in keys {
        let Some(theirs) = base.get(&key) else {
            continue;
        };
        let here = if path.is_empty() {
            key.clone()
        } else {
            format!("{path}.{key}")
        };
        match (doc.get_mut(&key), theirs) {
            (Some(Value::Table(ours)), Value::Table(theirs)) => {
                keep_tables(ours, theirs, &here, kept);
                if ours.is_empty() {
                    doc.remove(&key);
                }
            }
            _ => {
                doc.remove(&key);
                kept.push(here);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Rendering, checking, and writing
// ---------------------------------------------------------------------------

pub fn render(out: &Output, source: &Path) -> String {
    let body = serde_yaml::to_string(&Value::Table(out.doc.clone())).unwrap_or_default();
    format!(
        "{MARKER}\n# Source: {} ({}).\n# Edit freely; `sofka import k9s --force` replaces this file.\n{body}",
        source.display(),
        out.label
    )
}

/// Run the generated text through sofka's own config validation, so a
/// translation sofka would reject or warn about is reported now.
fn check(text: &str, effective: Option<&Value>) -> Result<Vec<String>, String> {
    let cfg =
        crate::config::parse_yaml(text).map_err(|e| format!("invalid generated config: {e}"))?;
    let mut warnings = crate::config::plugin_warnings(&cfg.plugins);
    warnings.extend(crate::config::bookmark_warnings(&cfg.bookmarks));
    // Keys come from the config the file is merged into, so the user's own
    // rebindings decide which imported keys a built-in action takes first.
    let merged: Option<crate::config::Config> = effective.and_then(|v| v.clone().try_into().ok());
    let keys = merged.as_ref().map_or(&cfg.keys, |m| &m.keys);
    if let Ok(keymap) = crate::keymap::Keymap::compile(keys) {
        warnings.extend(crate::keymap::hidden_bindings(
            &keymap,
            &cfg.plugins,
            &cfg.bookmarks,
            &cfg.workspaces,
        ));
    }
    warnings.extend(crate::views::compile(&cfg.views).1);
    Ok(warnings)
}

fn summary(doc: &Table) -> String {
    let count = |key: &str| match doc.get(key) {
        Some(Value::Array(a)) => a.len(),
        Some(Value::Table(t)) => t.len(),
        _ => 0,
    };
    let mut parts = Vec::new();
    for (key, one, many) in [
        ("aliases", "alias", "aliases"),
        ("plugins", "plugin", "plugins"),
        ("bookmarks", "bookmark", "bookmarks"),
        ("views", "view", "views"),
        (
            "favorite_namespaces",
            "favorite namespace",
            "favorite namespaces",
        ),
    ] {
        match count(key) {
            0 => {}
            1 => parts.push(format!("1 {one}")),
            n => parts.push(format!("{n} {many}")),
        }
    }
    for key in doc.keys() {
        if !matches!(
            key.as_str(),
            "aliases" | "plugins" | "bookmarks" | "views" | "favorite_namespaces" | "plugins_merge"
        ) {
            parts.push(key.replace('_', " "));
        }
    }
    parts.join(", ")
}

fn generated(path: &Path) -> bool {
    std::fs::read_to_string(path).is_ok_and(|t| t.starts_with(MARKER))
}

/// Write (or, with `dry_run`, print) the planned files under `dir` and return
/// the report. A file sofka did not generate is never replaced; a file an
/// earlier import generated is replaced only with `force`.
pub fn apply(plan: &Plan, dir: &Path, dry_run: bool, force: bool) -> Result<Vec<String>, String> {
    let mut report = vec![format!(
        "Reading k9s configuration from {}",
        plan.source.display()
    )];
    let earlier = generated_files(dir);
    if !force && let Some(path) = earlier.first() {
        return Err(format!(
            "{} was written by an earlier import; rerun with --force to replace it",
            path.display()
        ));
    }
    // With a k9s file unread, every output may lack its settings: replacing
    // or removing an earlier import could drop a read-only flag or the
    // bookmarks a context inherits. A first import has nothing to lose.
    if !earlier.is_empty() && !plan.unreadable.is_empty() {
        let files: Vec<String> = plan
            .unreadable
            .iter()
            .map(|p| p.display().to_string())
            .collect();
        return Err(format!(
            "cannot read {}; fix or remove it and rerun, nothing was changed",
            files.join(", ")
        ));
    }
    let mut skipped = plan.skipped.clone();
    let mut writes = Vec::new();
    for out in &plan.outputs {
        let target = dir.join(&out.path);
        let siblings: Vec<PathBuf> = ["config.toml", "config.yml"]
            .iter()
            .map(|n| target.with_file_name(n))
            .filter(|p| out.path.starts_with("clusters") && p.exists())
            .collect();
        if let Some(other) = siblings.first() {
            skipped.push(format!(
                "{}: {} already exists; add these settings to it by hand",
                out.label,
                other.display()
            ));
            continue;
        }
        if target.exists() && !generated(&target) {
            skipped.push(format!(
                "{}: {} exists and was not written by the importer; left unchanged",
                out.label,
                target.display()
            ));
            continue;
        }
        writes.push((target, out));
    }
    // A file an earlier import wrote that this import no longer produces
    // would keep its old settings active.
    let stale: Vec<&PathBuf> = earlier
        .iter()
        .filter(|p| !writes.iter().any(|(t, _)| t == *p))
        .collect();

    // Render and validate everything before writing anything.
    let mut rendered = Vec::new();
    let mut problems = Vec::new();
    for (target, out) in &writes {
        let text = render(out, &plan.source);
        let effective = if out.path == Path::new(DROPIN) {
            plan.effective.clone()
        } else {
            plan.effective
                .clone()
                .map(|e| crate::config::merge_layers([e, Value::Table(out.doc.clone())]))
        };
        let warnings = check(&text, effective.as_ref())
            .map_err(|e| format!("{}: {e}; nothing was written", out.path.display()))?;
        problems.extend(
            warnings
                .into_iter()
                .map(|w| format!("{}: {w}", out.path.display())),
        );
        rendered.push((target, out, text));
    }

    if writes.is_empty() && stale.is_empty() {
        report.push("Nothing to import.".into());
    }
    let (write, remove) = if dry_run {
        ("Would write", "Would remove")
    } else {
        ("Wrote", "Removed")
    };
    for (target, out, text) in &rendered {
        if dry_run {
            report.push(format!("--- {}", target.display()));
            report.extend(text.lines().map(String::from));
        } else {
            crate::atomicfile::write(target, text)?;
        }
        report.push(format!(
            "{write} {} ({})",
            target.display(),
            summary(&out.doc)
        ));
    }
    for path in stale {
        if !dry_run {
            std::fs::remove_file(path).map_err(|e| format!("{}: {e}", path.display()))?;
        }
        report.push(format!(
            "{remove} {} (an earlier import wrote it; nothing replaces it now)",
            path.display()
        ));
    }
    if !plan.kept.is_empty() {
        report.push("Kept your sofka settings for:".into());
        report.extend(plan.kept.iter().map(|k| format!("  - {k}")));
    }
    if !skipped.is_empty() {
        report.push("Not imported:".into());
        report.extend(skipped.iter().map(|s| format!("  - {s}")));
    }
    if !problems.is_empty() {
        report.push("sofka reported these problems with the result:".into());
        report.extend(problems.iter().map(|p| format!("  - {p}")));
    }
    if !writes.is_empty() && !dry_run {
        report.push("Start sofka and run :config to review the merged configuration.".into());
    }
    Ok(report)
}

/// Files an earlier import wrote: the drop-in and context overrides that
/// still carry the importer's marker.
fn generated_files(dir: &Path) -> Vec<PathBuf> {
    let mut found = vec![dir.join(DROPIN)];
    for cluster in subdirs(&dir.join("clusters")) {
        for context in subdirs(&cluster) {
            found.push(context.join("config.yaml"));
        }
    }
    found.retain(|p| generated(p));
    found
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(tag: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("sofka-k9s-import-{}-{tag}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn put(dir: &Path, rel: &str, text: &str) {
        let path = dir.join(rel);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, text).unwrap();
    }

    fn plugin(yaml: &str) -> K9sPlugin {
        serde_yaml::from_str(yaml).unwrap()
    }

    fn strings(v: &Value) -> Vec<&str> {
        v.as_array()
            .unwrap()
            .iter()
            .map(|s| s.as_str().unwrap())
            .collect()
    }

    #[test]
    fn k9s_key_names_become_sofka_chords() {
        assert_eq!(chord("Shift-L").as_deref(), Some("L"));
        assert_eq!(chord("Shift-1").as_deref(), Some("!"));
        assert_eq!(chord("Shift-0").as_deref(), Some(")"));
        assert_eq!(chord("Ctrl-T").as_deref(), Some("ctrl-t"));
        assert_eq!(chord("a").as_deref(), Some("a"));
        assert_eq!(chord("F5").as_deref(), Some("f5"));
        assert_eq!(chord("PgDn").as_deref(), Some("pgdn"));
        assert_eq!(chord("Backspace2").as_deref(), Some("backspace"));
        assert_eq!(chord("Shift-F5"), None);
        assert_eq!(chord("Hyper-X"), None);
    }

    #[test]
    fn simple_jsonpaths_become_json_pointers() {
        for (path, pointer) in [
            (".spec.nodeName", "/spec/nodeName"),
            ("{.spec.containers[0].image}", "/spec/containers/0/image"),
            ("spec.replicas", "/spec/replicas"),
            ("$.status.phase", "/status/phase"),
            (
                ".metadata.labels.app\\.kubernetes\\.io/name",
                "/metadata/labels/app.kubernetes.io~1name",
            ),
            (
                ".metadata.annotations['example.com/team']",
                "/metadata/annotations/example.com~1team",
            ),
            (".status.conditions[1].type", "/status/conditions/1/type"),
        ] {
            assert_eq!(json_pointer(path).as_deref(), Some(pointer), "{path}");
        }
        for path in [
            ".spec.containers[*].image",
            ".status.conditions[?(@.type==\"Ready\")].status",
            "..name",
            ".spec.ports[0:2]",
            "",
        ] {
            assert_eq!(json_pointer(path), None, "{path}");
        }
    }

    #[test]
    fn shell_plugins_keep_their_script_with_sofka_placeholders() {
        let p = plugin(
            r#"
shortCut: Shift-L
description: stern
scopes: [po, apps/v1/deployments, all]
command: bash
background: false
args: [-c, "stern ${NAME} -n $namespace --context $CONTEXT -o $RESOURCE_NAME.$RESOURCE_GROUP/$RESOURCE_VERSION"]
"#,
        );
        let (out, notes) = convert_plugin("stern", &p).unwrap();
        assert!(notes.is_empty(), "{notes:?}");
        assert_eq!(out["key"].as_str(), Some("L"));
        assert_eq!(out["command"].as_str(), Some("bash"));
        assert_eq!(
            strings(&out["args"]),
            [
                "-c",
                "stern $NAME -n $NAMESPACE --context $CONTEXT -o $RESOURCE.$GROUP/$VERSION"
            ]
        );
        assert!(!out.contains_key("scopes"), "`all` means every resource");
        assert_eq!(out["mutating"].as_bool(), Some(false));
        assert!(!out.contains_key("output"));
    }

    #[test]
    fn plugin_scopes_normalize_to_plurals() {
        let p = plugin(
            "shortCut: x\nscopes: [po, apps/v1/deployments, v1/services, containers]\ncommand: echo\n",
        );
        let (out, notes) = convert_plugin("x", &p).unwrap();
        assert_eq!(strings(&out["scopes"]), ["pods", "deployments", "services"]);
        assert!(notes.iter().any(|n| n.contains("containers")), "{notes:?}");
    }

    #[test]
    fn dangerous_plugins_stay_out_of_read_only_mode() {
        let p = plugin(
            "shortCut: Ctrl-K\nscopes: [pods]\ncommand: kubectl\ndangerous: true\nbackground: true\nconfirm: true\nargs: [delete, pod, $NAME]\n",
        );
        let (out, _) = convert_plugin("kill", &p).unwrap();
        assert_eq!(out["mutating"].as_bool(), Some(true));
        assert_eq!(out["confirm"].as_bool(), Some(true));
        assert_eq!(out["output"].as_str(), Some("background"));
        assert_eq!(out["key"].as_str(), Some("ctrl-k"));
    }

    #[test]
    fn plugins_that_cannot_work_are_skipped_with_a_reason() {
        for (yaml, reason) in [
            (
                "shortCut: a\nscopes: [pods]\ncommand: sh\nargs: [-c, echo $COL-STATUS]\n",
                "table cells",
            ),
            (
                "shortCut: a\nscopes: [containers]\ncommand: sh\nargs: [-c, echo $POD]\n",
                "containers",
            ),
            (
                "shortCut: a\nscopes: [pods]\ncommand: sh\npipes: [jq]\n",
                "pipes",
            ),
            ("shortCut: Shift-F1\nscopes: [pods]\ncommand: sh\n", "key"),
            (
                "shortCut: a\nscopes: [pods]\ncommand: sh\nargs: [-c, echo $!FLAG]\n",
                "inverted",
            ),
            (
                "shortCut: a\nscopes: [pods]\ncommand: sh\nargs: [-c, \"echo $INPUT_TAIL\"]\ninputs: [{name: TAIL, type: number}]\n",
                "whole arguments",
            ),
        ] {
            let err = convert_plugin("p", &plugin(yaml)).unwrap_err();
            assert!(err.contains(reason), "{yaml}: {err}");
        }
    }

    #[test]
    fn plugin_inputs_become_validated_inputs() {
        let p = plugin(
            r#"
shortCut: t
scopes: [pods]
command: kubectl
args: [logs, $NAME, --tail, $INPUT_TAIL, --container, "${INPUT_CONTAINER}"]
inputs:
  - {name: TAIL, type: number, required: true, default: 100}
  - {name: CONTAINER, type: dropdown, options: [app, sidecar]}
  - {name: VERBOSE, type: bool}
"#,
        );
        let (out, _) = convert_plugin("tail", &p).unwrap();
        assert_eq!(
            strings(&out["args"]),
            [
                "logs",
                "$NAME",
                "--tail",
                "${input.TAIL}",
                "--container",
                "${input.CONTAINER}"
            ]
        );
        assert_eq!(out["inputs"]["TAIL"]["default"].as_str(), Some("100"));
        assert_eq!(
            strings(&out["inputs"]["CONTAINER"]["choices"]),
            ["app", "sidecar"]
        );
        assert_eq!(
            out["confirm"].as_bool(),
            Some(true),
            "k9s confirms plugins with inputs"
        );
        assert_eq!(out["prompt"].as_str(), Some("always"));
    }

    #[test]
    fn kubeconfig_placeholders_are_reported_not_dropped() {
        let p = plugin(
            "shortCut: a\nscopes: [pods]\ncommand: bash\nargs: [-c, \"kubectl --kubeconfig $KUBECONFIG get pod $NAME\"]\n",
        );
        let (out, notes) = convert_plugin("p", &p).unwrap();
        assert!(strings(&out["args"])[1].contains("$KUBECONFIG"));
        assert!(
            notes[0].contains("$KUBECONFIG left to the shell environment"),
            "{notes:?}"
        );
    }

    #[test]
    fn view_columns_map_to_builtins_metrics_and_paths() {
        let mut views = BTreeMap::new();
        views.insert(
            "v1/pods".to_string(),
            View {
                sort_column: Some("AGE:desc".into()),
                columns: vec![
                    "NAME".into(),
                    "NAMESPACE|WR".into(),
                    "%CPU/R".into(),
                    "IMAGE:.spec.containers[0].image|W".into(),
                    "STARTED:.status.startTime|T".into(),
                    "IP|H".into(),
                    "BAD:.spec.containers[*].name".into(),
                ],
            },
        );
        let (mut doc, mut skipped) = (Table::new(), Vec::new());
        convert_views(&views, &mut doc, &mut skipped);
        let view = &doc["views"]["v1/pods"];
        assert_eq!(view["sort"].as_str(), Some("AGE:desc"));
        assert_eq!(view["replace"].as_bool(), Some(true));
        let cols = view["columns"].as_array().unwrap();
        assert_eq!(
            cols.len(),
            5,
            "hidden and untranslatable columns are dropped"
        );
        assert_eq!(cols[0]["builtin"].as_str(), Some("NAME"));
        assert_eq!(cols[1]["wide"].as_bool(), Some(true));
        assert_eq!(cols[1]["align"].as_str(), Some("right"));
        assert_eq!(cols[2]["metric"].as_str(), Some("cpu-request-utilization"));
        assert_eq!(cols[3]["path"].as_str(), Some("/spec/containers/0/image"));
        assert_eq!(cols[4]["type"].as_str(), Some("time"));
        assert!(skipped[0].contains("BAD"), "{skipped:?}");
    }

    #[test]
    fn hotkeys_and_destination_aliases_become_bookmarks() {
        let file: HotkeyFile = serde_yaml::from_str(
            r#"
hotKeys:
  shift-1: {shortCut: Shift-1, command: dp}
  ingress: {shortCut: Shift-2, command: "ing kube-system @prod"}
  ctx: {shortCut: Shift-3, command: ctx}
"#,
        )
        .unwrap();
        let (mut doc, mut skipped) = (Table::new(), Vec::new());
        convert_hotkeys(&file.hot_keys, &mut doc, &mut skipped);
        let mut aliases = BTreeMap::new();
        aliases.insert("web".to_string(), "pods default app=web".to_string());
        aliases.insert(
            "cert".to_string(),
            "cert-manager.io/v1/certificates".to_string(),
        );
        aliases.insert("dp".to_string(), "deployments".to_string());
        convert_aliases(&aliases, &mut doc, &mut skipped);

        let bookmarks = doc["bookmarks"].as_array().unwrap();
        assert_eq!(bookmarks.len(), 3);
        assert_eq!(bookmarks[0]["name"].as_str(), Some("ingress"));
        assert_eq!(bookmarks[0]["key"].as_str(), Some("@"));
        assert_eq!(bookmarks[0]["namespace"].as_str(), Some("kube-system"));
        assert_eq!(bookmarks[0]["context"].as_str(), Some("prod"));
        assert_eq!(bookmarks[1]["key"].as_str(), Some("!"));
        assert_eq!(bookmarks[1]["resource"].as_str(), Some("dp"));
        assert_eq!(bookmarks[2]["filter"].as_str(), Some("-l app=web"));
        assert!(bookmarks[2].get("key").is_none());
        assert_eq!(
            doc["aliases"]["cert"].as_str(),
            Some("certificates.cert-manager.io")
        );
        assert!(doc["aliases"].get("dp").is_none(), "sofka already has dp");
        assert!(skipped[0].contains("\"ctx\""), "{skipped:?}");
    }

    #[test]
    fn only_settings_changed_from_k9s_defaults_are_imported() {
        let main: MainFile = serde_yaml::from_str(
            r#"
k9s:
  readOnly: false
  refreshRate: 2
  defaultView: dp
  ui: {enableMouse: true, headless: false, skin: gruvbox-dark-hard}
  logger: {tail: 100, buffer: 5000, sinceSeconds: 300}
  thresholds:
    cpu: {critical: 90, warn: 70}
    memory: {critical: 95, warn: 80}
  imageScans: {enable: true}
"#,
        )
        .unwrap();
        let (mut doc, mut skipped) = (Table::new(), Vec::new());
        convert_settings(&main.k9s, &mut doc, &mut skipped);
        assert!(doc.get("readonly").is_none());
        assert_eq!(doc["default_resource"].as_str(), Some("dp"));
        assert_eq!(doc["mouse"].as_bool(), Some(true));
        assert_eq!(doc["skin"]["name"].as_str(), Some("gruvbox-dark"));
        assert_eq!(doc["logs"]["since"].as_str(), Some("300s"));
        assert!(doc["logs"].get("tail").is_none());
        assert_eq!(
            doc["thresholds"]["utilization"]["warn"].as_integer(),
            Some(80)
        );
        assert!(skipped.iter().any(|s| s.contains("gruvbox-dark-hard")));
        assert!(skipped.iter().any(|s| s.contains("imageScans")));
    }

    #[test]
    fn existing_sofka_settings_win_over_imported_ones() {
        let base: Value = toml::from_str(
            r#"
mouse = false
[skin]
name = "nord"
[[plugins]]
name = "stern"
key = "L"
command = "stern"
[[bookmarks]]
name = "Mine"
key = "!"
resource = "pods"
"#,
        )
        .unwrap();
        let mut doc: Table = toml::from_str(
            r#"
mouse = true
default_resource = "dp"
[skin]
name = "dracula"
background = true
[[plugins]]
name = "stern"
key = "S"
command = "stern"
[[plugins]]
name = "dive"
key = "D"
command = "dive"
[[bookmarks]]
name = "deploys"
key = "!"
resource = "dp"
[[bookmarks]]
name = "ing"
key = "@"
resource = "ing"
"#,
        )
        .unwrap();
        let (mut kept, mut skipped) = (Vec::new(), Vec::new());
        keep_base(&mut doc, base.as_table().unwrap(), &mut kept, &mut skipped);
        assert!(doc.get("mouse").is_none());
        assert_eq!(doc["default_resource"].as_str(), Some("dp"));
        assert!(doc["skin"].get("name").is_none());
        assert_eq!(doc["skin"]["background"].as_bool(), Some(true));
        let plugins = doc["plugins"].as_array().unwrap();
        assert_eq!(plugins.len(), 1);
        assert_eq!(plugins[0]["name"].as_str(), Some("dive"));
        let names: Vec<_> = doc["bookmarks"]
            .as_array()
            .unwrap()
            .iter()
            .map(|b| b["name"].as_str().unwrap())
            .collect();
        assert_eq!(names, ["Mine", "ing"], "base bookmarks survive the drop-in");
        assert_eq!(kept, ["plugin \"stern\"", "mouse", "skin.name"]);
        assert!(skipped[0].contains("deploys"));
    }

    #[test]
    fn k9s_directories_follow_its_xdg_lookup() {
        let home = Some(PathBuf::from("/home/u"));
        let none = |_: &str| None;
        let (config, data) = candidates(Platform::Linux, none, home.clone());
        assert_eq!(config, [PathBuf::from("/home/u/.config/k9s")]);
        assert_eq!(data, [PathBuf::from("/home/u/.local/share/k9s")]);

        let (config, _) = candidates(Platform::MacOs, none, home.clone());
        assert_eq!(
            config,
            [
                PathBuf::from("/home/u/Library/Application Support/k9s"),
                PathBuf::from("/home/u/.config/k9s"),
            ]
        );

        let xdg = |name: &str| (name == "XDG_CONFIG_HOME").then(|| "/x".into());
        assert_eq!(
            candidates(Platform::MacOs, xdg, home.clone()).0[0],
            PathBuf::from("/x/k9s")
        );

        let pinned = |name: &str| (name == "K9S_CONFIG_DIR").then(|| "/k".into());
        assert_eq!(
            candidates(Platform::Linux, pinned, home),
            (vec![PathBuf::from("/k")], vec![PathBuf::from("/k")])
        );
    }

    fn k9s_fixture(k9s: &Path) {
        put(
            k9s,
            "config.yaml",
            "k9s:\n  readOnly: false\n  ui:\n    skin: dracula\n",
        );
        put(
            k9s,
            "aliases.yaml",
            "%YAML 1.1\n---\naliases:\n  aliases:\n    cert: cert-manager.io/v1/certificates\n",
        );
        put(
            k9s,
            "plugins.yaml",
            "plugins:\n  stern:\n    shortCut: Shift-L\n    description: logs\n    scopes: [po]\n    command: stern\n    args: [$NAME, -n, $NAMESPACE]\n",
        );
        put(
            k9s,
            "plugins/dive.yaml",
            "shortCut: Shift-D\ndescription: dive\nscopes: [po]\ncommand: dive\nargs: [$NAME]\n",
        );
        put(
            k9s,
            "hotkeys.yaml",
            "hotKeys:\n  deploys:\n    shortCut: Shift-1\n    command: dp\n",
        );
        put(
            k9s,
            "views.yaml",
            "views:\n  v1/pods:\n    sortColumn: AGE:desc\n    columns: [NAME, STATUS, \"NODE:.spec.nodeName\", AGE]\n",
        );
        put(
            k9s,
            "clusters/arn-aws-eks-eu-west-1-1-cluster-prod/prod-admin/config.yaml",
            "k9s:\n  cluster: prod\n  readOnly: true\n  namespace:\n    active: web\n    lockFavorites: true\n    favorites: [web, all]\n",
        );
        put(
            k9s,
            "clusters/kind/kind-dev/config.yaml",
            "k9s:\n  cluster: kind\n  readOnly: false\n  namespace:\n    active: default\n    lockFavorites: false\n    favorites: [default, web, staging]\n",
        );
    }

    #[test]
    fn import_writes_files_sofka_loads() {
        let root = scratch("e2e");
        let (k9s, sofka) = (root.join("k9s"), root.join("sofka"));
        k9s_fixture(&k9s);
        put(&sofka, "config.toml", "default_namespace = \"web\"\n");

        let src = Sources::at(&k9s).unwrap();
        let loader = crate::config::ConfigLoader::from_dir(Some(sofka.clone()));
        let plan = plan(&src, &UserConfig::read(&loader));
        let report = apply(&plan, &sofka, false, false).unwrap();
        let problems: Vec<_> = report
            .iter()
            .filter(|l| l.starts_with("  - conf.d"))
            .collect();
        assert_eq!(
            problems,
            [
                "  - conf.d/00-k9s.yaml: plugin \"stern\": L is hidden by keys.table.provider_logs when that action is available"
            ],
            "a built-in key that takes an imported one is reported"
        );
        assert!(sofka.join(DROPIN).is_file());
        assert!(
            !sofka.join("clusters/kind").exists(),
            "contexts with only k9s state get no file"
        );

        let loader = crate::config::ConfigLoader::from_dir(Some(sofka.clone()));
        let cfg = loader.resolve("", "").config;
        assert_eq!(cfg.default_namespace.as_deref(), Some("web"));
        assert_eq!(cfg.skin.name.as_deref(), Some("dracula"));
        assert_eq!(
            cfg.aliases.get("cert").map(String::as_str),
            Some("certificates.cert-manager.io")
        );
        let names: Vec<_> = cfg.plugins.iter().map(|p| p.name.as_str()).collect();
        assert!(
            names.contains(&"stern") && names.contains(&"dive"),
            "{names:?}"
        );
        let stern = cfg.plugins.iter().find(|p| p.name == "stern").unwrap();
        assert_eq!(stern.scopes, ["pods"]);
        assert_eq!(stern.mutating, Some(false));
        assert_eq!(cfg.bookmarks[0].key.as_deref(), Some("!"));
        assert!(crate::config::plugin_warnings(&cfg.plugins).is_empty());
        let (views, warnings) = crate::views::compile(&cfg.views);
        assert!(warnings.is_empty(), "{warnings:?}");
        assert!(!views.is_empty());

        let prod = loader
            .resolve("prod-admin", "arn:aws:eks:eu-west-1:1:cluster/prod")
            .config;
        assert!(prod.readonly);
        assert_eq!(prod.favorite_namespaces, ["web"]);
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn reimport_needs_force_and_never_replaces_user_files() {
        let root = scratch("reimport");
        let (k9s, sofka) = (root.join("k9s"), root.join("sofka"));
        k9s_fixture(&k9s);
        let src = Sources::at(&k9s).unwrap();
        let plan = plan(&src, &UserConfig::default());
        apply(&plan, &sofka, false, false).unwrap();

        let err = apply(&plan, &sofka, false, false).unwrap_err();
        assert!(err.contains("--force"), "{err}");
        let err = apply(&plan, &sofka, true, false).unwrap_err();
        assert!(
            err.contains("--force"),
            "a dry run previews what the same flags allow"
        );
        apply(&plan, &sofka, false, true).unwrap();

        let dropin = sofka.join(DROPIN);
        std::fs::write(&dropin, "mouse = false\n").unwrap();
        let ctx = sofka.join("clusters/arn-aws-eks-eu-west-1-1-cluster-prod/prod-admin");
        std::fs::remove_file(ctx.join("config.yaml")).unwrap();
        std::fs::write(ctx.join("config.toml"), "readonly = false\n").unwrap();
        let report = apply(&plan, &sofka, false, true).unwrap();
        assert_eq!(std::fs::read_to_string(&dropin).unwrap(), "mouse = false\n");
        assert!(!ctx.join("config.yaml").exists());
        assert!(
            report
                .iter()
                .any(|l| l.contains("not written by the importer"))
        );
        assert!(
            report
                .iter()
                .any(|l| l.contains("config.toml already exists"))
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn dry_run_prints_and_writes_nothing() {
        let root = scratch("dry");
        let (k9s, sofka) = (root.join("k9s"), root.join("sofka"));
        k9s_fixture(&k9s);
        let plan = plan(&Sources::at(&k9s).unwrap(), &UserConfig::default());
        let report = apply(&plan, &sofka, true, false).unwrap();
        assert!(!sofka.exists());
        assert!(report.iter().any(|l| l == MARKER));
        assert!(report.iter().any(|l| l.starts_with("Would write")));
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn imported_input_defaults_pass_sofka_validation() {
        let p = plugin(
            "shortCut: t\nscopes: [pods]\ncommand: echo\nargs: [$INPUT_C, $INPUT_V, $INPUT_S]\ninputs:\n  - {name: C, type: dropdown, options: [app, sidecar]}\n  - {name: V, type: bool}\n  - {name: S, type: string}\n",
        );
        let (out, _) = convert_plugin("t", &p).unwrap();
        for (name, spec) in out["inputs"].as_table().unwrap() {
            let input: crate::plugins::Input = spec.clone().try_into().unwrap();
            let default = input.default.clone().unwrap();
            assert_eq!(input.validate(&default), Ok(()), "{name}: {default:?}");
        }
        assert_eq!(out["inputs"]["C"]["default"].as_str(), Some("app"));
    }

    #[test]
    fn threshold_note_names_the_band_it_used() {
        for (yaml, used) in [
            (
                "k9s:\n  thresholds:\n    cpu: {critical: 95, warn: 80}\n",
                "used the CPU values, not the memory values",
            ),
            (
                "k9s:\n  thresholds:\n    memory: {critical: 95, warn: 80}\n",
                "used the memory values, not the CPU values",
            ),
        ] {
            let main: MainFile = serde_yaml::from_str(yaml).unwrap();
            let (mut doc, mut skipped) = (Table::new(), Vec::new());
            convert_settings(&main.k9s, &mut doc, &mut skipped);
            assert_eq!(
                doc["thresholds"]["utilization"]["warn"].as_integer(),
                Some(80)
            );
            assert!(skipped[0].contains(used), "{skipped:?}");
        }
    }

    #[test]
    fn a_plugins_directory_alone_is_a_k9s_config() {
        let root = scratch("plugins-only");
        assert!(!holds_k9s_config(&root));
        put(
            &root,
            "plugins/dive.yaml",
            "shortCut: d\nscopes: [po]\ncommand: dive\n",
        );
        assert!(holds_k9s_config(&root));
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn earlier_user_drop_ins_and_key_rebindings_win() {
        let root = scratch("dropins");
        let (k9s, sofka) = (root.join("k9s"), root.join("sofka"));
        k9s_fixture(&k9s);
        put(&sofka, "conf.d/00-a-team.yaml", "skin:\n  name: nord\n");
        put(
            &sofka,
            "config.toml",
            "[keys.table]\nprovider_logs = \"alt-l\"\n",
        );
        let loader = crate::config::ConfigLoader::from_dir(Some(sofka.clone()));
        let plan = plan(&Sources::at(&k9s).unwrap(), &UserConfig::read(&loader));
        assert!(
            plan.kept.contains(&"skin.name".to_string()),
            "{:?}",
            plan.kept
        );
        let report = apply(&plan, &sofka, false, false).unwrap();
        assert!(
            !report.iter().any(|l| l.contains("is hidden by")),
            "the user moved provider_logs off L: {report:#?}"
        );
        let cfg = crate::config::ConfigLoader::from_dir(Some(sofka.clone()))
            .resolve("", "")
            .config;
        assert_eq!(cfg.skin.name.as_deref(), Some("nord"));
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn context_hotkeys_keep_inherited_bookmarks() {
        let root = scratch("ctx-hotkeys");
        let (k9s, sofka) = (root.join("k9s"), root.join("sofka"));
        put(
            &k9s,
            "clusters/kind/kind-dev/hotkeys.yaml",
            "hotKeys:\n  ing:\n    shortCut: Shift-2\n    command: ing\n",
        );
        put(
            &k9s,
            "clusters/kind/kind-dev/aliases.yaml",
            "aliases:\n  web: pods default app=web\n",
        );
        put(
            &sofka,
            "config.toml",
            "[[bookmarks]]\nname = \"Mine\"\nresource = \"pods\"\n",
        );
        let loader = crate::config::ConfigLoader::from_dir(Some(sofka.clone()));
        let plan = plan(&Sources::at(&k9s).unwrap(), &UserConfig::read(&loader));
        apply(&plan, &sofka, false, false).unwrap();
        let cfg = crate::config::ConfigLoader::from_dir(Some(sofka.clone()))
            .resolve("kind-dev", "kind")
            .config;
        let names: Vec<_> = cfg.bookmarks.iter().map(|b| b.name.as_str()).collect();
        assert_eq!(names, ["Mine", "web", "ing"]);
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn forced_reimport_removes_files_nothing_replaces() {
        let root = scratch("stale");
        let (k9s, sofka) = (root.join("k9s"), root.join("sofka"));
        k9s_fixture(&k9s);
        let src = Sources::at(&k9s).unwrap();
        apply(&plan(&src, &UserConfig::default()), &sofka, false, false).unwrap();
        let prod = "clusters/arn-aws-eks-eu-west-1-1-cluster-prod/prod-admin/config.yaml";
        assert!(sofka.join(prod).is_file());

        put(
            &k9s,
            "clusters/arn-aws-eks-eu-west-1-1-cluster-prod/prod-admin/config.yaml",
            "k9s:\n  readOnly: false\n",
        );
        let plan = plan(&src, &UserConfig::default());
        let report = apply(&plan, &sofka, true, true).unwrap();
        assert!(report.iter().any(|l| l.starts_with("Would remove")));
        assert!(sofka.join(prod).is_file(), "a dry run removes nothing");
        apply(&plan, &sofka, false, true).unwrap();
        assert!(!sofka.join(prod).exists());
        let cfg = crate::config::ConfigLoader::from_dir(Some(sofka.clone()))
            .resolve("prod-admin", "arn:aws:eks:eu-west-1:1:cluster/prod")
            .config;
        assert!(!cfg.readonly);
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn invalid_generated_config_writes_nothing() {
        let root = scratch("invalid");
        let mut bad = Table::new();
        bad.insert("readonly".into(), "yes".into());
        let plan = Plan {
            source: root.join("k9s"),
            outputs: vec![
                Output {
                    path: PathBuf::from("clusters/a/b/config.yaml"),
                    doc: Table::from_iter([("mouse".to_string(), Value::from(true))]),
                    label: "fine".into(),
                },
                Output {
                    path: PathBuf::from(DROPIN),
                    doc: bad,
                    label: "broken".into(),
                },
            ],
            ..Plan::default()
        };
        let err = apply(&plan, &root, false, false).unwrap_err();
        assert!(err.contains("invalid generated config"), "{err}");
        assert!(!root.join("clusters").exists() && !root.join(DROPIN).exists());
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn unreadable_sources_stop_a_reimport() {
        let root = scratch("unreadable");
        let (k9s, sofka) = (root.join("k9s"), root.join("sofka"));
        k9s_fixture(&k9s);
        let ctx = "clusters/arn-aws-eks-eu-west-1-1-cluster-prod/prod-admin";
        put(
            &k9s,
            &format!("{ctx}/hotkeys.yaml"),
            "hotKeys:\n  ing:\n    shortCut: Shift-2\n    command: ing\n",
        );
        let src = Sources::at(&k9s).unwrap();
        apply(&plan(&src, &UserConfig::default()), &sofka, false, false).unwrap();
        let before = |p: &str| std::fs::read_to_string(sofka.join(p)).unwrap();
        let (dropin, prod) = (before(DROPIN), before(&format!("{ctx}/config.yaml")));

        // The context config breaks while its hotkeys still convert, and the
        // global hotkeys break while other global settings still convert.
        put(
            &k9s,
            &format!("{ctx}/config.yaml"),
            "k9s: [not, a, mapping\n",
        );
        put(&k9s, "hotkeys.yaml", "hotKeys: [\n");
        let plan = plan(&src, &UserConfig::default());
        assert_eq!(plan.unreadable.len(), 2, "{:?}", plan.unreadable);
        assert!(
            plan.outputs
                .iter()
                .any(|o| o.path.ends_with("prod-admin/config.yaml"))
        );
        for dry_run in [true, false] {
            let err = apply(&plan, &sofka, dry_run, true).unwrap_err();
            assert!(err.contains("nothing was changed"), "{err}");
        }
        assert_eq!(before(DROPIN), dropin);
        assert_eq!(before(&format!("{ctx}/config.yaml")), prod);
        let cfg = crate::config::ConfigLoader::from_dir(Some(sofka.clone()))
            .resolve("prod-admin", "arn:aws:eks:eu-west-1:1:cluster/prod")
            .config;
        assert!(cfg.readonly, "the context stays read-only");
        assert!(
            cfg.bookmarks.iter().any(|b| b.name == "deploys"),
            "global bookmarks survive"
        );
        let _ = std::fs::remove_dir_all(&root);
    }
}
